README.md
lib/analytics.dart
lib/asset/asset.dart
lib/cloudinary.dart
lib/src/transformation/delivery/delivery.dart
lib/src/transformation/delivery/delivery_actions.dart
test/tests_utils.dart
test/transformation/delivery_test.dart
test/url_test.dart

Remove `generate` function from being public and setting it into override of `toString()`

Remove generate function

---

lib/src/transformation/delivery/delivery_actions.dart
lib/src/transformation/resize/resize.dart
lib/src/transformation/resize/scale.dart
test/transformation/delivery_test.dart
test/transformation/resize_test.dart

Update `Scale` syntax

---

lib/src/transformation/delivery/delivery_actions.dart
lib/src/transformation/resize/fit.dart
lib/src/transformation/resize/resize.dart
test/transformation/delivery_test.dart
test/transformation/resize_test.dart

Update `Fit` syntax

---

lib/asset/asset.dart
lib/asset/builders/asset_builder.dart
lib/asset/builders/general_asset_builder.dart
lib/asset/builders/image_builder.dart
lib/asset/builders/video_builder.dart
lib/asset/image.dart
lib/asset/video.dart
lib/src/transformation/common.dart
lib/src/transformation/transformation.dart
test/url_test.dart

Add transformation as an object to the `Asset` class so we can start using the Transformation Builder

Implement transformation in url generation

---

lib/asset/asset.dart
lib/asset/builders/asset_builder.dart
lib/asset/builders/general_asset_builder.dart
lib/asset/builders/image_builder.dart
lib/asset/builders/video_builder.dart
lib/cloudinary.dart
test/url_test.dart

Improve syntax for `GeneralAssetBuilder` to align with all other builders

Update `GeneralAssetBuilder` syntax

---

lib/src/transformation/resize/fit.dart
lib/src/transformation/resize/resize.dart
lib/src/transformation/resize/scale.dart
test/transformation/resize_test.dart

Add `MinimumFit` and `LimitFit` actions

Add `MinimumFit` and `LimitFit` actions

---

lib/transformation/gravity/focus_on.dart
lib/transformation/gravity/gravity.dart
test/transformation/resize_test.dart

Fix `FocusOn` to string bug

---

lib/transformation/delivery/delivery_actions.dart
test/transformation/delivery_test.dart
test/transformation/trasnformation_test.dart

Remove consts, and move quality values to functions

Fix quality

---

url_gen/lib/analytics.dart
url_gen/lib/cloudinary.dart
url_gen/pubspec.yaml
url_gen/test/analytics_test.dart

Fix an issue where analytics takes tech version with patch version

Fix analytics issue

---

url_gen/lib/transformation/transformation.dart
url_gen/test/transformation/trasnformation_test.dart

Add support for `addTransfomration` alias

Add add transformation support

---

url_gen/lib/transformation/gravity/gravity.dart
url_gen/test/transformation/resize_test.dart

Fix gravity values based on the git issue #73

Fix gravity values

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add zoompan action support

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add generative replace action

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add generative restore

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add missing parameter to generative remove transformation

Update generative remove

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Update generative replace parameters

Update generative replace

---

url_gen/lib/analytics.dart
url_gen/test/analytics_test.dart

Fix analytics token when version string give less than 2 valid values

Fix analytics token

---

url_gen/lib/transformation/delivery/delivery.dart
url_gen/lib/transformation/delivery/delivery_actions.dart
url_gen/test/transformation/delivery_test.dart

Add `density` action

---

url_gen/lib/transformation/delivery/delivery.dart
url_gen/lib/transformation/delivery/delivery_actions.dart
url_gen/test/transformation/delivery_test.dart

Add `colorspace` from icc action

Add `colorspace` from icc action

---

url_gen/lib/transformation/delivery/delivery.dart
url_gen/lib/transformation/delivery/delivery_actions.dart
url_gen/test/transformation/delivery_test.dart

Add default image action

---

url_gen/lib/transformation/delivery/delivery.dart
url_gen/lib/transformation/delivery/delivery_actions.dart
url_gen/test/transformation/delivery_test.dart

Add `colorSpace` action

---

url_gen/lib/analytics/analytics.dart
url_gen/lib/analytics/analytics_helper.dart

Fix `Platform` usage on web

---

api/lib/src/request/model/uploader_params.dart
api/lib/src/response/upload_result.dart
api/test/uploader_test.dart

Add media metadata support to upload and explicit

Add media metadata support

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add enhance action support

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add `e_upscale` action support

Add upscale action support

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add blur faces and blur region actions support

Add blur faces and blur region actions support

---

url_gen/lib/transformation/resize/crop.dart
url_gen/lib/transformation/resize/resize.dart
url_gen/test/transformation/resize_test.dart

Add crop auto action support

---

url_gen/lib/transformation/resize/pad.dart
url_gen/lib/transformation/resize/resize.dart
url_gen/test/transformation/resize_test.dart

Add auto pad action
- [ x] Adds more tests

Add auto pad action

---

url_gen/lib/transformation/effect/effect.dart
url_gen/lib/transformation/effect/effect_actions.dart
url_gen/test/transformation/effect_test.dart

Add generative background replace action

Add generative background replace action

---

api/lib/src/request/model/uploader_params.dart
api/test/uploader_test.dart

Add missing notification_url to rename params

Add missing notification_url to rename params

---

api/lib/src/request/model/uploader_params.dart
api/lib/uploader/uploader.dart
api/test/uploader_test.dart

Add destroy 

---

api/lib/src/request/model/uploader_params.dart
api/lib/uploader/uploader.dart
api/lib/uploader/uploader_utils.dart
api/test/uploader_test.dart
tools/get_test_cloud.sh

Add download backup support

---

api/lib/src/request/model/uploader_params.dart
api/lib/src/response/upload_result.dart
api/test/uploader_test.dart

Add auto chaptering and auto transcription to Upload Api

Add auto chaptering and auto transcription to Upload Api

---

api/lib/src/response/upload_result.dart

Fixed parsing field "bytes" in UploadResult.

---

url_gen/lib/config/cloud_config.dart

Add signature version to cloud config

Add signature version to cloud config

---

.github/workflows/cloudinary_dart.yml

Fix github actions script
